// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BGoodsItem: typeof import('./components/business/goods-item/b-goods-item.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XCarousel: typeof import('./components/carousel/x-carousel.vue')['default']
    XCitySelector: typeof import('./components/selector/x-city-selector.vue')['default']
    XExhibitMagnifier: typeof import('./components/exhibit/x-exhibit-magnifier.vue')['default']
    XInfiniteLoading: typeof import('./components/loading/x-infinite-loading.vue')['default']
    XSkeleton: typeof import('./components/layout/x-skeleton.vue')['default']
    XStaticCheckbox: typeof import('./components/form/x-static-checkbox.vue')['default']
    XThemeModeButton: typeof import('./components/buttons/x-theme-mode-button.vue')['default']
  }
}
